# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tracking
tagline:          'A Jekyll theme'
description:      ''
url:              https://aknottymathematician.github.io/
baseurl:          /

author:
  name:           'A Knotty Mathematician'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/aknottymathematician/Tracking
